caption = {
"english":[
"Sham's Electric Bill Counter", 
["Existing Bills"], 
["Create New", "Bills"], 
"Enter the name for the new bill:", 
"^ This name is already taken:", 
"Are you sure you want to exit?", 
"Do you want to save the following file?", 
["Cancel"], 
["OK"], 
"Home", 
"Add", 
"Remove", 
"Edit",
"Checkout", 
"Settings",
"Move", 
"Enter the name for the appliance:", 
"Enter the WattPerHour used for the appliance:", 
"Enter the hours used for the appliance in a day:", 
"Enter the new name for the appliance:",
"Name of appliance to edit:", 
"^ Name not found:", 
"Appliance name:",
"WPH:",
"Hours:", 
"Name of appliance to remove:",
"The total cost of this meter is:", 
"^ The input must be a number:", 
"Back", 
"Add Meter",
"Remove Meter",
"Edit Meter",
"Toggle Language",
"Toggle Dark Mode", 
"Check Total Of All Meters", 
"Meters:", 
"Enter the name for the meter:", 
"Name of meter to be removed:", 
"^ This meter cannot be removed:", 
"Name of meter to edit:", 
"Enter the new name for the meter:", 
"^ This meter cannot be edited:", 
"The total cost of all meters is:", 
"Remove Bill",
"Edit Bill",
"Enter the name of the bill to delete:", 
"Bill Name:", 
"Name of appliance to be moved:", 
"Name of meter to move to:",
"This name already exists, please rename it:", 
"Name of bill to edit:", 
"Enter the new name for the bill:",
"The total cost of all meters with tax is:", 
"The total cost of this meter with tax is:",
"Enter the rate of SST: (in decimals)",
"Enter the rate of KWTBB: (in decimals)",
"Enter the total amount of days spanned:", 
"SST:", 
"KWTBB:", 
"Days:"
],

"malay":[
"Penghitung Bil Elektrik Sham", 
["Bil Yang", "Wujud"],
["Cipta Bil", "Baru"],
"Berikan nama untuk bil baharu:", 
"^ Nama ini sedang digunakan:", 
"Adakan anda hendak keluar?", 
"Adakan anda hendak menyimpan fail tersebut?", 
["Batal"], 
["Setuju"], 
"Menu Utama", 
"Tambah", 
"Keluarkan", 
"Ubah",
"Bayar", 
"Tetapan", 
"Pindah",
"Masukkan nama untuk perkakasan:", 
"Masukkan WattPerJam untuk perkakasan:", 
"Masukkan bil. jam perkakasan diguna dlm sehari:", 
"Masukkan nama baharu perkakasan:", 
"Nama perkakasan yang akan diubah:",
"^ Nama tidak dapat dicari:", 
"Nama perkakasan:",
"WPJ:",
"Jam:",
"Nama perkakasan yang akan dikeluar:", 
"Kos untuk meter ini adalah:", 
"^ Input tersebut mestilah nombor", 
"Balik",
"Tambah Meter",
"Keluar Meter", 
"Ubah Meter", 
"Tukar Bahasa", 
"Tukar Mod Warna", 
"Semak Kos Untuk Seluruh Bil", 
"Semua Meter:", 
"Masukkan nama untuk meter:", 
"Nama meter untuk dikeluar:", 
"^ Nama ini tidak boleh dikeluarkan:",
"Nama meter untuk diubah:", 
"Masukkan nama baru untuk meter:", 
"^ Nama ini tidak boleh diubah:",
"Kos untuk seluruh bil adalah:",
"Buang Bil",
"Ubah Bil",
"Masukkan nama bil untuk dibuang:", 
"Nama Bil:", 
"Nama perkakasan untuk dipindah:", 
"Nama meter untuk dipindah:",
"Nama telah wujud, tolong beri nama lain:", 
"Nama bil yang akan diubah:", 
"Masukkan nama baru untuk bil:",
"Kos untuk seluruh bil dengan cukai adalah:", 
"Kos untuk meter ini dengan cukai adalah:",
"Masukkan kadar SST: (dlm perpuluhan)",
"Masukkan kadar KWTBB: (dlm perpuluhan)",
"Masukkan jumlah hari sepanjang bil:", 
"SST:", 
"KWTBB:", 
"Hari:"
]
}